import ContextWindow
import ContextWindowOpenAI
import Foundation
import Observation

// MARK: - GPTService

/// The OpenAI / GPT integration's view-model and boundary.
///
/// Owns the chat session as a single `ContextWindow` actor backed by a
/// `SQLiteContextStore` in `Application Support/DJRoomba/assistant.sqlite`
/// (separate file from the library DB — same GRDB engine, no schema
/// intersection). The window is built lazily on first interaction so a
/// launch with no API key never touches the disk.
///
/// **Multi-conversation** (Phase 1.5, 2026-05-29 evening). The window
/// hosts many named contexts via the library's built-in
/// `listContexts` / `switchContext` / `createContext`. Each conversation
/// = one library `Context`. App-side title storage lives in
/// `AssistantConversationStore` (UserDefaults); titles are generated by
/// a separate `gpt-5.4-mini` call (`AssistantSummarizer`) when the user
/// hits **New Request**, which archives the just-finished conversation
/// and mints a fresh one.
///
/// Tools dispatch to ``MusicController`` through a `weak` reference
/// captured by the tool closures (`GPTToolRegistration.tools`). The tool
/// table is a window-level concern (in-memory dict on the
/// `ContextWindow` actor); registering once after building the window
/// is enough — the executor exposes them across every conversation
/// switch.
///
/// `@MainActor @Observable` per the project's state rules.
@MainActor
@Observable
final class GPTService {

  // MARK: Lifecycle

  init(store: LibraryStore? = nil, catalogIngest: CatalogIngestService? = nil) {
    self.store = store
    self.catalogIngest = catalogIngest
    let storedKey = (try? keychain.read()) ?? nil
    isKeyConfigured = storedKey != nil
  }

  // MARK: Internal

  /// Per-turn reasoning-effort override for the chat model.
  ///
  /// Maps 1:1 to OpenAI's `reasoning_effort` wire values (DJROOMBA
  /// PATCH 3 in `OpenAIChatModel`). `.default` aliases `.medium` —
  /// the server default — and is special-cased to OMIT the wire
  /// field entirely so a default-effort turn produces the cleanest
  /// possible request body (and avoids implying intent the user
  /// didn't express). Higher = slower + more deliberate.
  enum ReasoningEffort: String, CaseIterable, Sendable {
    case minimal
    case low
    case medium
    case high

    // MARK: Internal

    /// Alias for the user-visible "default" state — sends nothing on
    /// the wire and lets the server pick (medium).
    static let `default` = ReasoningEffort.medium

    /// Wire representation for `OpenAIChatModel.reasoningEffort`.
    /// `.default` returns `nil` so the field is omitted from the
    /// request body entirely; non-default values send their literal
    /// raw string.
    var wireValue: String? {
      self == .default ? nil : rawValue
    }

    /// Compact label for the segmented picker chrome.
    var shortLabel: String {
      switch self {
      case .minimal: "Min"
      case .low: "Low"
      case .medium: "Med"
      case .high: "High"
      }
    }
  }

  /// One rendered turn in the chat transcript.
  struct Message: Identifiable, Equatable, Sendable {
    enum Role: Sendable, Equatable {
      case user
      case assistant
      /// A tool call or tool output — surfaced italicised in the UI so the
      /// user can see what the model decided to fetch.
      case tool
    }

    let id: Int64
    let role: Role
    let content: String
    let timestamp: Date
  }

  /// OpenAI `service_tier` for the chat model. `"flex"` opts into the
  /// cheaper / higher-latency tier — DJ Roomba is a deliberate,
  /// user-initiated surface but not latency-sensitive, so flex is a
  /// straight cost win. Requires the DJROOMBA PATCH 2 vendor change to
  /// `OpenAIChatModel`. (`nil` would fall back to the default tier.)
  /// `nonisolated` so `AssistantSummarizer` (its own non-actor enum)
  /// can read it without an actor hop.
  nonisolated static let serviceTier = "flex"

  /// Shared `URLSession` for both the chat model and the summarizer,
  /// configured with extended timeouts because the flex tier can sit
  /// in queue for a while. The user's reference example used 900 s;
  /// we mirror that. Held as a static `let` so the configuration is
  /// computed exactly once per process. `nonisolated` so the
  /// summarizer can read it without hopping to the main actor.
  nonisolated static let urlSession: URLSession = {
    let configuration = URLSessionConfiguration.default
    configuration.timeoutIntervalForRequest = 900
    configuration.timeoutIntervalForResource = 1800
    return URLSession(configuration: configuration)
  }()

  /// UserDefaults key for the Phase-5 auto-fill opt-in. Owned here
  /// so the view (`OpenAISettingsPane` via `@AppStorage`) and the
  /// controller's drain detector key off one canonical string.
  nonisolated static let autoFillToggleKey = "djroomba.upNext.autoFillEnabled"

  /// Seed prompt for the Phase-5 auto-fill loop. Sent verbatim as
  /// the first user message of a fresh conversation when the Up
  /// Next queue drains and the user has the opt-in toggle on. Kept
  /// tight — the system prompt's "auto-fill" paragraph teaches the
  /// model to fulfil this silently without preamble; this seed
  /// just supplies the context the system prompt promised would
  /// arrive. `static let` so the system prompt's auto-fill
  /// paragraph and this seed stay easy to read side-by-side.
  static let autoFillSeed = """
    The Up Next queue is running low and I need eleven more tracks. \
    Use `recently_played` (and `app_state` if useful) to pick what \
    I'm likely to want next, then add 11 tracks via `up_next_add` \
    in a single call. Don't ask follow-up questions — just queue them.
    """

  /// Per-turn reasoning effort override for the chat model. Drives
  /// OpenAI's `reasoning_effort` request field on gpt-5.x (DJROOMBA
  /// PATCH 3). The assistant pane's segmented picker writes here
  /// before each `sendMessage`; the turn body applies the value to
  /// `chatModel.reasoningEffort` and unconditionally resets this
  /// property back to `.default` in `defer` so cancellations and
  /// errors snap back too. `.default` ⇒ omit the wire field
  /// entirely, server default (medium) applies.
  var pendingReasoningEffort = ReasoningEffort.default

  /// Whether an API key is stored in the Keychain.
  private(set) var isKeyConfigured: Bool

  /// Visible chat transcript for the *current* conversation. System
  /// prompts are filtered out — they're for the model, not the user.
  private(set) var messages = [Message]()

  /// True while a `callModel()` is in flight.
  private(set) var isSending = false

  /// Human-readable error from the last save / send, if any.
  private(set) var errorMessage: String?

  /// Sidebar feed — every assistant conversation present in the
  /// underlying SQLite store, joined with our titles + last-activity
  /// hints. Sorted by `lastActivityAt` descending so the most recent is
  /// at the top. Empty until `refreshConversations()` has run once
  /// (which happens during `ensureSession()` and after every mutation).
  private(set) var conversations = [ConversationListEntry]()

  /// The library context name backing the visible chat. `nil` until the
  /// first session is built; thereafter persisted to UserDefaults so a
  /// relaunch resumes the same conversation.
  private(set) var currentConversationID: String?

  /// Late-binds `MusicController` so the assistant's playback / state
  /// tools (`play_playlist`, `play_track`, `app_state`, …) can reach
  /// the controller. Held weakly inside the service so the controller
  /// remains the sole owner — controller → gpt is `let`, gpt →
  /// controller is `weak`.
  func attach(controller: MusicController) {
    hostController = controller
  }

  /// Persist (or overwrite) the API key. Trims whitespace; ignores empty.
  /// A key rotation tears down the active session so the next send
  /// rebuilds with the new credential.
  func saveKey(_ raw: String) {
    let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return }
    do {
      try keychain.save(trimmed)
      isKeyConfigured = true
      errorMessage = nil
      session = nil
    } catch {
      errorMessage = "Couldn’t save the key — \(error)"
    }
  }

  /// Forget the stored key, drop the in-memory session, and clear the
  /// rendered transcript. Underlying SQLite records remain on disk; a
  /// future re-add reopens the same context. (Deliberate — the user can
  /// rotate a key without losing history.)
  func clearKey() {
    do {
      try keychain.delete()
      isKeyConfigured = false
      session = nil
      messages = []
      errorMessage = nil
    } catch {
      errorMessage = "Couldn’t remove the key — \(error)"
    }
  }

  /// Append `text` to the conversation and drive `callModel()`. Tool
  /// calls fire inside the model's loop and are persisted as records;
  /// the transcript refresh at the tail surfaces everything.
  ///
  /// Cancellable: the actual model loop runs inside `inFlightTurn` so
  /// `cancelTurn()` can drop the wait via Swift structured concurrency.
  /// `Task.checkCancellation()` lands at the next suspension inside the
  /// `ContextWindow.callModel()` loop (HTTP request, tool-call dispatch,
  /// or the loop's own `await`s). The in-flight HTTP request may
  /// complete on the server side after we cancel — we just stop waiting
  /// on it and surface a synthetic "Turn cancelled." row in the
  /// transcript so the user sees what happened.
  func sendMessage(_ text: String) async {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return }
    guard inFlightTurn == nil else { return }

    isSending = true
    errorMessage = nil

    AssistantLog.logger.info("→ user: \(AssistantLog.truncate(trimmed), privacy: .public)")

    // DJROOMBA PATCH 3 wiring: snapshot the user's pending choice so the
    // turn body can apply it independently of any later mutation; the
    // `defer` snap-back fires on success, cancel, AND throw so the
    // segmented picker always returns to its default position after the
    // turn settles. Snap-back happens BEFORE `isSending` flips false so
    // the UI sees the reset and the spinner disappear in one frame.
    let effortForTurn = pendingReasoningEffort
    let turn = Task { @MainActor [weak self] in
      guard let self else { return }
      defer {
        self.pendingReasoningEffort = .default
        self.isSending = false
        self.inFlightTurn = nil
      }
      do {
        let session = try await ensureSession()
        // Apply the per-turn effort to the shared chat model right
        // before driving the loop. The model is a value-typed `var`
        // on `OpenAIChatModel`; we're on the main actor and so are
        // any other writers (`@MainActor`-isolated `GPTService`), so
        // no separate synchronisation is needed.
        session.chatModel.reasoningEffort = effortForTurn.wireValue
        try Task.checkCancellation()
        try await session.window.addPrompt(trimmed)
        // Optimistic refresh so the user sees their own message immediately.
        await refreshTranscript(window: session.window)
        try Task.checkCancellation()
        let reply = try await session.window.callModel()
        try Task.checkCancellation()
        AssistantLog.logger.info("← assistant: \(AssistantLog.truncate(reply), privacy: .public)")
        await refreshTranscript(window: session.window)
        if let currentID = currentConversationID {
          AssistantConversationStore.setLastActivity(.now, for: currentID)
        }
        refreshConversations()
      } catch is CancellationError {
        AssistantLog.logger.info("✕ turn cancelled by user")
        appendCancelledMarker()
      } catch {
        if Task.isCancelled {
          AssistantLog.logger.info("✕ turn cancelled by user (post-throw)")
          appendCancelledMarker()
        } else {
          AssistantLog.logger.error("! send failed: \(String(describing: error), privacy: .public)")
          errorMessage = "\(error)"
          if let session {
            await refreshTranscript(window: session.window)
          }
        }
      }
    }
    inFlightTurn = turn
    await turn.value
  }

  /// Cancel the in-flight model turn, if any. Swift structured
  /// concurrency propagates cancellation through `ContextWindow.callModel`
  /// — `Task.checkCancellation()` lands at the next suspension point
  /// (the in-flight HTTP request, the next tool-call dispatch, or one of
  /// the loop's `await`s). The server-side completion isn't aborted;
  /// we just stop waiting for it and discard the reply. A synthetic
  /// "Turn cancelled." marker is appended to the transcript inside the
  /// turn's cancel branch so the user sees what happened.
  func cancelTurn() {
    guard let task = inFlightTurn else { return }
    AssistantLog.logger.info("→ user cancelled turn")
    task.cancel()
    inFlightTurn = nil
  }

  /// Re-pull the transcript from the underlying context window. Cheap
  /// on modest chat lengths (an indexed read on one context id); we
  /// lean on this rather than tracking model events twice.
  func refreshTranscript() async {
    guard let session else { return }
    await refreshTranscript(window: session.window)
  }

  /// Best-effort, no-API-key-required load of the sidebar feed (+ the
  /// current conversation pointer if not yet known) directly from
  /// `assistant.sqlite`. Used by the assistant pane's `.task` so the
  /// sidebar populates with existing conversations the moment the
  /// pane appears — `ensureSession()` is otherwise lazy and only runs
  /// on first send.
  ///
  /// Quiet on every error: a missing file (first launch) or a
  /// transient SQLite hiccup leaves the in-memory list empty rather
  /// than throwing into the UI.
  func loadConversationsFromDisk() {
    do {
      let url = try Self.contextStoreURL()
      let contextStore = try SQLiteContextStore(path: url.path)
      // Create the `contexts` / `records` / `context_tools` tables on
      // first run (and migrate forward via the vendored library's
      // `CREATE TABLE IF NOT EXISTS` ladder, idempotent on an
      // already-initialised file). Without this, opening
      // `assistant.sqlite` on a machine that's never had it before
      // throws "no such table: contexts" the moment we call
      // `listContexts()` — `ContextWindow.init` calls `initialize()`
      // itself, but `loadConversationsFromDisk()` runs *before*
      // `ensureSession()` builds the window, so we must do it here too.
      try contextStore.initialize()
      let raw = try contextStore.listContexts()
        .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }
      let titles = AssistantConversationStore.titles()
      let activity = AssistantConversationStore.lastActivity()
      conversations = raw
        .map { context in
          ConversationListEntry(
            id: context.name,
            title: titles[context.name],
            startedAt: context.startTime,
            lastActivityAt: activity[context.name] ?? context.startTime,
          )
        }
        .sorted { $0.lastActivityAt > $1.lastActivityAt }
      if currentConversationID == nil {
        if
          let stored = AssistantConversationStore.currentContextName(),
          raw.contains(where: { $0.name == stored })
        {
          currentConversationID = stored
        } else if let mostRecent = raw.max(by: { $0.startTime < $1.startTime }) {
          currentConversationID = mostRecent.name
        }
      }
      // Pre-populate the visible transcript for whichever conversation
      // the sidebar is pointing at — same SQLite store, no API key
      // required, so the chat surface reflects the user's last state
      // the moment the pane appears (without this, the transcript
      // stays empty until they pick the conversation explicitly OR
      // send a message that builds the session).
      if let id = currentConversationID {
        loadTranscriptFromDisk(contextName: id, store: contextStore)
      }
    } catch {
      // First launch / file not yet created — sidebar stays empty,
      // which is the correct empty-state, not an error.
    }
  }

  /// Read records for `contextName` directly out of the SQLite store
  /// and project them into `messages`, bypassing the `ContextWindow`
  /// session. Used in two places: at view-appear from
  /// `loadConversationsFromDisk` (no API key needed), and as the fast
  /// path inside `switchConversation` so a sidebar click updates the
  /// transcript immediately even when `ensureSession()` would block
  /// on a missing key or a transient build error. Quiet on every
  /// error: leaves `messages` as a sensible empty list rather than
  /// throwing into the UI.
  func loadTranscriptFromDisk(contextName: String, store: SQLiteContextStore? = nil) {
    do {
      let contextStore: SQLiteContextStore
      if let store {
        contextStore = store
      } else {
        let url = try Self.contextStoreURL()
        contextStore = try SQLiteContextStore(path: url.path)
        try contextStore.initialize()
      }
      let context = try contextStore.getContext(name: contextName)
      let records = try contextStore.listRecords(contextID: context.id)
      messages = records.compactMap { Self.message(from: $0) }
    } catch {
      messages = []
    }
  }

  /// Archive the current conversation (kicks off background
  /// summarization if it has user turns) and mint a fresh empty one.
  /// No-op if the current conversation has no user turns yet — the
  /// user just hit New Request on something they hadn't started, so
  /// there's nothing to archive.
  func newConversation() async {
    let session: Session
    do {
      session = try await ensureSession()
    } catch {
      AssistantLog.logger.error("! newConversation prereq: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }

    let archivedID = currentConversationID
    let archivedMessages = messages
    let archivedHasUserTurn = archivedMessages.contains { $0.role == .user }

    let freshName = AssistantConversationStore.mintContextName()
    do {
      try await session.window.createContext(name: freshName)
      try await session.window.setSystemPrompt(Self.systemPrompt)
    } catch {
      AssistantLog.logger.error("! newConversation create: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }

    currentConversationID = freshName
    AssistantConversationStore.setCurrentContextName(freshName)
    AssistantConversationStore.setLastActivity(.now, for: freshName)
    messages = []
    refreshConversations()

    if archivedHasUserTurn, let archivedID, !archivedMessages.isEmpty {
      summarizeInBackground(messages: archivedMessages, for: archivedID)
    }
  }

  /// Phase-5 auto-fill dispatch (`plans/up-next-queue.md` — "Auto-fill
  /// on queue low-water"). Called by
  /// `MusicController.notifyUpNextMutated` when the queue depth crosses
  /// `UpNextDrainDetector.refillThreshold` (=1) on the way down, with
  /// the user's opt-in toggle on and the API key configured.
  /// Single-flight: if a previous auto-fill task is still running this
  /// call no-ops.
  ///
  /// The task mints a fresh conversation (the user explicitly wanted
  /// auto-fills isolated from any in-progress chat) and sends a tight
  /// seed message instructing the model to add 11 tracks via
  /// `recently_played` + `up_next_add`. The 11-track batch + 1-remaining
  /// trigger gives the assistant a song's worth of playback to land
  /// the refill, so the user doesn't sit through dead air between
  /// batches. Any failure inside `sendMessage` surfaces via the
  /// assistant pane's `errorMessage` just like a user-typed message
  /// would — we don't shadow-handle network errors here. The task
  /// handle is cleared in `defer` so a re-cross after a clean fill
  /// re-arms.
  func autoFillUpNext() {
    guard autoFillTask == nil else { return }
    AssistantLog.logger.info("→ auto-fill: queue at low-water, dispatching")
    autoFillTask = Task { @MainActor [weak self] in
      defer { self?.autoFillTask = nil }
      guard let self else { return }
      await newConversation()
      // Auto-fill should never inherit whatever per-turn effort the
      // user had pending on the chat surface — it's a background
      // refill, not a user turn. Force `.default` for the duration
      // of the seed send; `sendMessage`'s own `defer` will also reset
      // afterwards, which is fine (idempotent).
      pendingReasoningEffort = .default
      await sendMessage(Self.autoFillSeed)
    }
  }

  /// Permanently delete the conversation named `id`. Drops its
  /// records from `assistant.sqlite` via the vendored library's
  /// `deleteContext(name:)`, clears the app-side title + last-
  /// activity caches, and (if the deleted conversation was the
  /// current one) follows the library's "switch to the next-earliest
  /// context, or mint a fresh one" rule and adopts that name as the
  /// new current. Failure logs + surfaces in `errorMessage` but
  /// leaves visible state consistent — the refreshConversations()
  /// pass at the tail snaps the sidebar back to reality.
  func deleteConversation(_ id: String) async {
    let session: Session
    do {
      session = try await ensureSession()
    } catch {
      AssistantLog.logger.error("! deleteConversation prereq: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }
    let wasCurrent = currentConversationID == id
    do {
      try await session.window.deleteContext(name: id)
    } catch {
      AssistantLog.logger.error("! deleteContext \(id, privacy: .public): \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }
    AssistantConversationStore.clearTitle(for: id)
    AssistantConversationStore.clearLastActivity(for: id)
    if wasCurrent {
      // The library's deleteContext auto-switches the window to the
      // earliest remaining context (or mints a fresh one) — read
      // that back and adopt it as the new pointer.
      let nextName = await session.window.currentContext.name
      currentConversationID = nextName
      AssistantConversationStore.setCurrentContextName(nextName)
      // Re-apply the system prompt + reload the transcript onto the
      // adopted context so the chat surface tracks the switch.
      try? await session.window.setSystemPrompt(Self.systemPrompt)
      await refreshTranscript(window: session.window)
    }
    refreshConversations()
    AssistantLog.logger.info("✕ conversation deleted \(id, privacy: .public)")
  }

  /// Switch the visible chat to `id` (a library context name). Reads
  /// the transcript from disk and updates `messages`.
  func switchConversation(to id: String) async {
    // Update the visible pointer + load the transcript directly out of
    // SQLite right away. The previous code bailed when `id ==
    // currentConversationID`, but on launch `loadConversationsFromDisk`
    // sets `currentConversationID` from UserDefaults WITHOUT loading
    // the transcript (the session is lazy), so clicking the "already
    // selected" row in the sidebar did nothing — the chat stayed
    // empty even though the conversation had content. The disk read
    // is cheap and idempotent: re-clicking just re-reads the same
    // records into `messages`.
    currentConversationID = id
    AssistantConversationStore.setCurrentContextName(id)
    loadTranscriptFromDisk(contextName: id)
    refreshConversations()

    // Then build / switch the session for future sends. Skipping
    // this when no API key is configured: the disk-load already
    // surfaced the visible state; we just can't send into it yet.
    guard isKeyConfigured else { return }
    do {
      let session = try await ensureSession()
      try await session.window.switchContext(name: id)
      try await session.window.setSystemPrompt(Self.systemPrompt)
      await refreshTranscript(window: session.window)
    } catch {
      AssistantLog.logger.error("! switchContext: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
    }
  }

  /// Re-render the sidebar feed from the library + the title /
  /// last-activity caches. Cheap (one `listContexts()` + one
  /// `UserDefaults` read for the two dicts). Called after every
  /// state-mutating operation.
  func refreshConversations() {
    guard let session else { return }
    do {
      let raw = try session.contextStore.listContexts()
      let titles = AssistantConversationStore.titles()
      let activity = AssistantConversationStore.lastActivity()
      conversations = raw
        .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }
        .map { context in
          ConversationListEntry(
            id: context.name,
            title: titles[context.name],
            startedAt: context.startTime,
            lastActivityAt: activity[context.name] ?? context.startTime,
          )
        }
        .sorted { $0.lastActivityAt > $1.lastActivityAt }
    } catch {
      AssistantLog.logger.error("! listContexts: \(String(describing: error), privacy: .public)")
    }
  }

  // MARK: Private

  /// Per-app-launch chat session. Owns the window + the late-bound
  /// executor (the executor is bound to the window at construction
  /// time) and the underlying context store (cached so the sidebar
  /// can list contexts without re-opening SQLite).
  private struct Session {
    let window: ContextWindow
    let executor: LateBoundToolExecutor
    let contextStore: SQLiteContextStore
    /// Held so per-turn mutations (`reasoningEffort`) land on the same
    /// instance the `ContextWindow` is driving — re-instantiating
    /// would require also re-binding through `ContextWindow`'s
    /// `Model`-typed init parameter, which we don't expose.
    let chatModel: OpenAIChatModel
  }

  /// The chat model. Bumped from `gpt-4.1-mini` to `gpt-5.4` on
  /// 2026-05-29 per user direction. Pulling this into Settings is a
  /// Phase-4 follow-up; for now everything assumes one model.
  /// (Distinct from `AssistantSummarizer.modelName`, which is
  /// `gpt-5.4-mini` for one-shot conversation titling.)
  private static let modelName = "gpt-5.4"

  /// The system prompt that grounds the model in this app's surface.
  /// Kept short and specific; tool affordances are described in each
  /// tool's own schema, not duplicated here. Applied on every
  /// conversation creation / switch via `setSystemPrompt` (which
  /// deadens any prior copy).
  private static let systemPrompt = """
    You are the assistant inside DJ Roomba, a Mac app that manages the \
    user's Apple Music library through a local SQLite store. You can read \
    playlists and tracks, search Apple Music's catalog, see recently \
    played history, and create new app-owned playlists. Prefer calling \
    tools over guessing. When you list tracks back to the user, keep \
    replies short and use plain prose, not large tables.

    Up Next is a transient in-memory queue that preempts the current \
    playlist: when the current song ends (or the user hits Next), the \
    queue head plays before normal playlist advance resumes. Manage it \
    with `up_next_add` / `up_next_remove` / `up_next_get` / \
    `up_next_count`. When the user asks to "play more like X", "queue \
    up some Y", or "add these to up next" — use `up_next_add` (after a \
    `search_apple_music` if you need ids), NOT `play_track` / \
    `play_playlist`, which would replace the active player queue. \
    Reach for `play_playlist` / `play_track` only when the user wants \
    to start playing something right now. If the user's first message \
    in a fresh conversation says the queue is running low and asks for \
    tracks, the user has auto-fill enabled — silently fulfil it by \
    adding 11 tracks via `recently_played` + `up_next_add`, no preamble.
    """

  @ObservationIgnored private var session: Session?
  @ObservationIgnored private let store: LibraryStore?
  @ObservationIgnored private let catalogIngest: CatalogIngestService?
  /// Grace-note-3 cancel handle. Set when `sendMessage` begins driving a
  /// turn, cleared in the task body's `defer` on completion *or*
  /// cancellation. The outer `await turn.value` in `sendMessage` keeps the
  /// caller's coroutine alive across cancellation so the synthetic
  /// "Turn cancelled." marker lands before `sendMessage` returns. A
  /// second `sendMessage` while a turn is in flight no-ops (matches the
  /// existing `isSending`-disabled composer).
  @ObservationIgnored private var inFlightTurn: Task<Void, Never>?
  /// Phase-5 single-flight guard. Holds the in-flight auto-fill task so
  /// a second drain-detector dispatch (e.g. the user pounding Clear
  /// twice while the first refill is still resolving) no-ops instead
  /// of racing a second `newConversation` + `sendMessage` against the
  /// first. Cleared in the task body's `defer` so a clean exit re-arms
  /// the next drain.
  @ObservationIgnored private var autoFillTask: Task<Void, Never>?
  /// Weak controller back-reference for the playback / state tools.
  /// Set via `attach(controller:)` immediately after `MusicController`
  /// finishes initializing this service.
  @ObservationIgnored private weak var hostController: MusicController?

  @ObservationIgnored private let keychain = KeychainItem(
    service: "org.sockpuppet.djroomba",
    account: "openai-api-key",
  )

  /// Map one `Record` to a visible `Message`. System prompts are hidden.
  private static func message(from record: Record) -> Message? {
    let role: Message.Role
    switch record.source {
    case .prompt:
      role = .user

    case .modelResponse:
      role = .assistant

    case .toolCall,
         .toolOutput:
      role = .tool

    case .systemPrompt:
      return nil
    }
    return Message(
      id: record.id,
      role: role,
      content: record.content,
      timestamp: record.timestamp,
    )
  }

  /// `~/Library/Application Support/DJRoomba/assistant.sqlite`, mirroring
  /// `AppDatabase.defaultURL()` but in its own file.
  private static func contextStoreURL() throws -> URL {
    let directory = URL.applicationSupportDirectory
      .appending(path: "DJRoomba", directoryHint: .isDirectory)
    try FileManager.default.createDirectory(
      at: directory,
      withIntermediateDirectories: true,
    )
    return directory.appending(
      path: "assistant.sqlite",
      directoryHint: .notDirectory,
    )
  }

  /// Pick which library context to open the window on. Priority:
  /// (1) the UserDefaults pointer (the user's last conversation, if it
  ///     still exists),
  /// (2) the most recent existing assistant context (so a user with
  ///     pre-multi-conversation history lands on it),
  /// (3) the legacy single-conversation name (so the first multi-
  ///     conversation launch on a vanilla install still gets the same
  ///     starting name as Phase 1),
  /// (4) a freshly-minted UUID name.
  ///
  /// Static so it doesn't capture `self` — `ensureSession` calls this
  /// before the `Session` exists.
  private static func pickInitialContextName(
    in store: SQLiteContextStore
  ) throws -> String {
    let existing = try store.listContexts()
      .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }

    if
      let stored = AssistantConversationStore.currentContextName(),
      existing.contains(where: { $0.name == stored })
    {
      return stored
    }
    if let mostRecent = existing.max(by: { $0.startTime < $1.startTime }) {
      return mostRecent.name
    }
    return AssistantConversationStore.legacyContextName
  }

  /// Build the session on first use. Idempotent — a successful call
  /// caches. Re-runs after a key rotation (`session = nil` in
  /// `saveKey`). Multi-conversation aware: opens the SQLite store,
  /// inspects existing contexts, and adopts the one stored in
  /// `AssistantConversationStore.currentContextName()` (or the most
  /// recent existing assistant context, or the legacy single-
  /// conversation name, or finally a freshly-minted one).
  private func ensureSession() async throws -> Session {
    if let session { return session }
    guard let key = (try? keychain.read()) ?? nil, !key.isEmpty else {
      throw GPTServiceError.noAPIKey
    }

    let url = try Self.contextStoreURL()
    let contextStore = try SQLiteContextStore(path: url.path)
    // Same first-run schema bootstrap as `loadConversationsFromDisk` —
    // `pickInitialContextName` reads `contexts` via `listContexts()`,
    // which 500s with "no such table" on a freshly-created
    // `assistant.sqlite`. `initialize()` is `CREATE TABLE IF NOT
    // EXISTS` end-to-end so this is idempotent on an existing file.
    // (`ContextWindow.init` further down also calls `initialize()`,
    // but we read the store before that, so explicit here.)
    try contextStore.initialize()
    let initialContextName = try Self.pickInitialContextName(in: contextStore)

    let executor = LateBoundToolExecutor()
    let model = try OpenAIChatModel(
      model: Self.modelName,
      apiKey: key,
      toolExecutor: executor,
      transport: URLSessionOpenAITransport(session: Self.urlSession),
      serviceTier: Self.serviceTier,
    )
    let window = try ContextWindow(
      store: contextStore,
      contextName: initialContextName,
      model: model,
    )
    executor.bind(window)

    // Apply the system prompt to whichever context we adopted; idempotent
    // (`setSystemPrompt` deadens any prior copy so a re-run never piles
    // them up).
    try await window.setSystemPrompt(Self.systemPrompt)

    // Tools see the controller through a weak provider closure — the
    // closure captures `self` weakly, and `self.hostController` is
    // already weak, so tools never extend the controller's lifetime.
    let toolList = GPTToolRegistration.tools(
      store: store,
      catalogIngest: catalogIngest,
      controllerProvider: { @MainActor [weak self] in self?.hostController },
    )
    for tool in toolList {
      try await window.registerTool(tool)
    }

    let session = Session(
      window: window,
      executor: executor,
      contextStore: contextStore,
      chatModel: model,
    )
    self.session = session
    currentConversationID = initialContextName
    AssistantConversationStore.setCurrentContextName(initialContextName)
    await refreshTranscript(window: window)
    refreshConversations()
    return session
  }

  /// Append a synthetic "Turn cancelled." row to the visible transcript
  /// (only — not persisted to `assistant.sqlite`). Real records carry
  /// positive `Int64` ids minted by SQLite; synthetic markers use a
  /// negative id derived from the epoch microsecond so they never
  /// collide with a real record and `ForEach`'s `Identifiable` diff is
  /// happy across the next transcript refresh (the negative-id row
  /// simply disappears on the next disk reload — that's the intended
  /// behaviour, the user has the visible confirmation and any
  /// subsequent send rebuilds from records).
  private func appendCancelledMarker() {
    let marker = Message(
      id: -Int64(Date().timeIntervalSince1970 * 1_000_000),
      role: .assistant,
      content: "Turn cancelled.",
      timestamp: .now,
    )
    messages.append(marker)
  }

  private func refreshTranscript(window: ContextWindow) async {
    do {
      let records = try await window.allRecords()
      messages = records.compactMap { Self.message(from: $0) }
    } catch {
      // A transcript refresh can't surface usefully — the underlying
      // error would have been raised by the action that just ran.
    }
  }

  /// Detach a summarizer task (gpt-5.4-mini) for the just-archived
  /// conversation. Failure surfaces only to the log — a missing title
  /// leaves the sidebar entry as "Untitled", which is a recoverable
  /// state, not an alert-worthy condition.
  private func summarizeInBackground(messages: [Message], for contextName: String) {
    guard let key = (try? keychain.read()) ?? nil, !key.isEmpty else { return }
    let snapshot = messages
    Task { [weak self] in
      do {
        let title = try await AssistantSummarizer.summarize(
          messages: snapshot,
          apiKey: key,
        )
        AssistantConversationStore.setTitle(title, for: contextName)
        AssistantLog.logger.info(
          "← summary[\(contextName, privacy: .public)]: \(title, privacy: .public)"
        )
        await MainActor.run {
          self?.refreshConversations()
        }
      } catch {
        AssistantLog.logger.error(
          "! summarize \(contextName, privacy: .public): \(String(describing: error), privacy: .public)"
        )
      }
    }
  }

}

// MARK: - GPTServiceError

/// Errors surfaced from `GPTService`'s own boundary (provider errors
/// are passed through verbatim from `ContextWindowOpenAI`).
enum GPTServiceError: Error, CustomStringConvertible {
  case noAPIKey

  var description: String {
    switch self {
    case .noAPIKey:
      "No API key is configured."
    }
  }
}
