import ContextWindow
import ContextWindowOpenAI
import Foundation
import Observation

// MARK: - GPTService

/// The OpenAI / GPT integration's view-model and boundary.
///
/// Owns the chat session as a single `ContextWindow` actor backed by a
/// `SQLiteContextStore` in `Application Support/DJRoomba/assistant.sqlite`
/// (separate file from the library DB — same GRDB engine, no schema
/// intersection). The window is built lazily on first interaction so a
/// launch with no API key never touches the disk.
///
/// **Multi-conversation** (Phase 1.5, 2026-05-29 evening). The window
/// hosts many named contexts via the library's built-in
/// `listContexts` / `switchContext` / `createContext`. Each conversation
/// = one library `Context`. App-side title storage lives in
/// `AssistantConversationStore` (UserDefaults); titles are generated by
/// a separate `gpt-5.4-mini` call (`AssistantSummarizer`) when the user
/// hits **New Request**, which archives the just-finished conversation
/// and mints a fresh one.
///
/// Tools dispatch to ``MusicController`` through a `weak` reference
/// captured by the tool closures (`GPTToolRegistration.tools`). The tool
/// table is a window-level concern (in-memory dict on the
/// `ContextWindow` actor); registering once after building the window
/// is enough — the executor exposes them across every conversation
/// switch.
///
/// `@MainActor @Observable` per the project's state rules.
@MainActor
@Observable
final class GPTService {

  // MARK: Lifecycle

  init(store: LibraryStore? = nil, catalogIngest: CatalogIngestService? = nil) {
    self.store = store
    self.catalogIngest = catalogIngest
    let storedKey = (try? keychain.read()) ?? nil
    isKeyConfigured = storedKey != nil
  }

  // MARK: Internal

  /// One rendered turn in the chat transcript.
  struct Message: Identifiable, Equatable, Sendable {
    enum Role: Sendable, Equatable {
      case user
      case assistant
      /// A tool call or tool output — surfaced italicised in the UI so the
      /// user can see what the model decided to fetch.
      case tool
    }

    let id: Int64
    let role: Role
    let content: String
    let timestamp: Date
  }

  /// OpenAI `service_tier` for the chat model. `"flex"` opts into the
  /// cheaper / higher-latency tier — DJ Roomba is a deliberate,
  /// user-initiated surface but not latency-sensitive, so flex is a
  /// straight cost win. Requires the DJROOMBA PATCH 2 vendor change to
  /// `OpenAIChatModel`. (`nil` would fall back to the default tier.)
  /// `nonisolated` so `AssistantSummarizer` (its own non-actor enum)
  /// can read it without an actor hop.
  nonisolated static let serviceTier = "flex"

  /// Shared `URLSession` for both the chat model and the summarizer,
  /// configured with extended timeouts because the flex tier can sit
  /// in queue for a while. The user's reference example used 900 s;
  /// we mirror that. Held as a static `let` so the configuration is
  /// computed exactly once per process. `nonisolated` so the
  /// summarizer can read it without hopping to the main actor.
  nonisolated static let urlSession: URLSession = {
    let configuration = URLSessionConfiguration.default
    configuration.timeoutIntervalForRequest = 900
    configuration.timeoutIntervalForResource = 1800
    return URLSession(configuration: configuration)
  }()

  /// Whether an API key is stored in the Keychain.
  private(set) var isKeyConfigured: Bool

  /// Visible chat transcript for the *current* conversation. System
  /// prompts are filtered out — they're for the model, not the user.
  private(set) var messages = [Message]()

  /// True while a `callModel()` is in flight.
  private(set) var isSending = false

  /// Human-readable error from the last save / send, if any.
  private(set) var errorMessage: String?

  /// Sidebar feed — every assistant conversation present in the
  /// underlying SQLite store, joined with our titles + last-activity
  /// hints. Sorted by `lastActivityAt` descending so the most recent is
  /// at the top. Empty until `refreshConversations()` has run once
  /// (which happens during `ensureSession()` and after every mutation).
  private(set) var conversations = [ConversationListEntry]()

  /// The library context name backing the visible chat. `nil` until the
  /// first session is built; thereafter persisted to UserDefaults so a
  /// relaunch resumes the same conversation.
  private(set) var currentConversationID: String?

  /// Late-binds `MusicController` so the assistant's playback / state
  /// tools (`play_playlist`, `play_track`, `app_state`, …) can reach
  /// the controller. Held weakly inside the service so the controller
  /// remains the sole owner — controller → gpt is `let`, gpt →
  /// controller is `weak`.
  func attach(controller: MusicController) {
    hostController = controller
  }

  /// Persist (or overwrite) the API key. Trims whitespace; ignores empty.
  /// A key rotation tears down the active session so the next send
  /// rebuilds with the new credential.
  func saveKey(_ raw: String) {
    let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return }
    do {
      try keychain.save(trimmed)
      isKeyConfigured = true
      errorMessage = nil
      session = nil
    } catch {
      errorMessage = "Couldn’t save the key — \(error)"
    }
  }

  /// Forget the stored key, drop the in-memory session, and clear the
  /// rendered transcript. Underlying SQLite records remain on disk; a
  /// future re-add reopens the same context. (Deliberate — the user can
  /// rotate a key without losing history.)
  func clearKey() {
    do {
      try keychain.delete()
      isKeyConfigured = false
      session = nil
      messages = []
      errorMessage = nil
    } catch {
      errorMessage = "Couldn’t remove the key — \(error)"
    }
  }

  /// Append `text` to the conversation and drive `callModel()`. Tool
  /// calls fire inside the model's loop and are persisted as records;
  /// the transcript refresh at the tail surfaces everything.
  func sendMessage(_ text: String) async {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return }

    isSending = true
    errorMessage = nil
    defer { isSending = false }

    AssistantLog.logger.info("→ user: \(AssistantLog.truncate(trimmed), privacy: .public)")

    do {
      let session = try await ensureSession()
      try await session.window.addPrompt(trimmed)
      // Optimistic refresh so the user sees their own message immediately.
      await refreshTranscript(window: session.window)
      let reply = try await session.window.callModel()
      AssistantLog.logger.info("← assistant: \(AssistantLog.truncate(reply), privacy: .public)")
      await refreshTranscript(window: session.window)
      if let currentID = currentConversationID {
        AssistantConversationStore.setLastActivity(.now, for: currentID)
      }
      refreshConversations()
    } catch {
      AssistantLog.logger.error("! send failed: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      if let session {
        await refreshTranscript(window: session.window)
      }
    }
  }

  /// Re-pull the transcript from the underlying context window. Cheap
  /// on modest chat lengths (an indexed read on one context id); we
  /// lean on this rather than tracking model events twice.
  func refreshTranscript() async {
    guard let session else { return }
    await refreshTranscript(window: session.window)
  }

  /// Best-effort, no-API-key-required load of the sidebar feed (+ the
  /// current conversation pointer if not yet known) directly from
  /// `assistant.sqlite`. Used by the assistant pane's `.task` so the
  /// sidebar populates with existing conversations the moment the
  /// pane appears — `ensureSession()` is otherwise lazy and only runs
  /// on first send.
  ///
  /// Quiet on every error: a missing file (first launch) or a
  /// transient SQLite hiccup leaves the in-memory list empty rather
  /// than throwing into the UI.
  func loadConversationsFromDisk() {
    do {
      let url = try Self.contextStoreURL()
      let contextStore = try SQLiteContextStore(path: url.path)
      // Create the `contexts` / `records` / `context_tools` tables on
      // first run (and migrate forward via the vendored library's
      // `CREATE TABLE IF NOT EXISTS` ladder, idempotent on an
      // already-initialised file). Without this, opening
      // `assistant.sqlite` on a machine that's never had it before
      // throws "no such table: contexts" the moment we call
      // `listContexts()` — `ContextWindow.init` calls `initialize()`
      // itself, but `loadConversationsFromDisk()` runs *before*
      // `ensureSession()` builds the window, so we must do it here too.
      try contextStore.initialize()
      let raw = try contextStore.listContexts()
        .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }
      let titles = AssistantConversationStore.titles()
      let activity = AssistantConversationStore.lastActivity()
      conversations = raw
        .map { context in
          ConversationListEntry(
            id: context.name,
            title: titles[context.name],
            startedAt: context.startTime,
            lastActivityAt: activity[context.name] ?? context.startTime,
          )
        }
        .sorted { $0.lastActivityAt > $1.lastActivityAt }
      if currentConversationID == nil {
        if
          let stored = AssistantConversationStore.currentContextName(),
          raw.contains(where: { $0.name == stored })
        {
          currentConversationID = stored
        } else if let mostRecent = raw.max(by: { $0.startTime < $1.startTime }) {
          currentConversationID = mostRecent.name
        }
      }
      // Pre-populate the visible transcript for whichever conversation
      // the sidebar is pointing at — same SQLite store, no API key
      // required, so the chat surface reflects the user's last state
      // the moment the pane appears (without this, the transcript
      // stays empty until they pick the conversation explicitly OR
      // send a message that builds the session).
      if let id = currentConversationID {
        loadTranscriptFromDisk(contextName: id, store: contextStore)
      }
    } catch {
      // First launch / file not yet created — sidebar stays empty,
      // which is the correct empty-state, not an error.
    }
  }

  /// Read records for `contextName` directly out of the SQLite store
  /// and project them into `messages`, bypassing the `ContextWindow`
  /// session. Used in two places: at view-appear from
  /// `loadConversationsFromDisk` (no API key needed), and as the fast
  /// path inside `switchConversation` so a sidebar click updates the
  /// transcript immediately even when `ensureSession()` would block
  /// on a missing key or a transient build error. Quiet on every
  /// error: leaves `messages` as a sensible empty list rather than
  /// throwing into the UI.
  func loadTranscriptFromDisk(contextName: String, store: SQLiteContextStore? = nil) {
    do {
      let contextStore: SQLiteContextStore
      if let store {
        contextStore = store
      } else {
        let url = try Self.contextStoreURL()
        contextStore = try SQLiteContextStore(path: url.path)
        try contextStore.initialize()
      }
      let context = try contextStore.getContext(name: contextName)
      let records = try contextStore.listRecords(contextID: context.id)
      messages = records.compactMap { Self.message(from: $0) }
    } catch {
      messages = []
    }
  }

  /// Archive the current conversation (kicks off background
  /// summarization if it has user turns) and mint a fresh empty one.
  /// No-op if the current conversation has no user turns yet — the
  /// user just hit New Request on something they hadn't started, so
  /// there's nothing to archive.
  func newConversation() async {
    let session: Session
    do {
      session = try await ensureSession()
    } catch {
      AssistantLog.logger.error("! newConversation prereq: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }

    let archivedID = currentConversationID
    let archivedMessages = messages
    let archivedHasUserTurn = archivedMessages.contains { $0.role == .user }

    let freshName = AssistantConversationStore.mintContextName()
    do {
      try await session.window.createContext(name: freshName)
      try await session.window.setSystemPrompt(Self.systemPrompt)
    } catch {
      AssistantLog.logger.error("! newConversation create: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }

    currentConversationID = freshName
    AssistantConversationStore.setCurrentContextName(freshName)
    AssistantConversationStore.setLastActivity(.now, for: freshName)
    messages = []
    refreshConversations()

    if archivedHasUserTurn, let archivedID, !archivedMessages.isEmpty {
      summarizeInBackground(messages: archivedMessages, for: archivedID)
    }
  }

  /// Permanently delete the conversation named `id`. Drops its
  /// records from `assistant.sqlite` via the vendored library's
  /// `deleteContext(name:)`, clears the app-side title + last-
  /// activity caches, and (if the deleted conversation was the
  /// current one) follows the library's "switch to the next-earliest
  /// context, or mint a fresh one" rule and adopts that name as the
  /// new current. Failure logs + surfaces in `errorMessage` but
  /// leaves visible state consistent — the refreshConversations()
  /// pass at the tail snaps the sidebar back to reality.
  func deleteConversation(_ id: String) async {
    let session: Session
    do {
      session = try await ensureSession()
    } catch {
      AssistantLog.logger.error("! deleteConversation prereq: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }
    let wasCurrent = currentConversationID == id
    do {
      try await session.window.deleteContext(name: id)
    } catch {
      AssistantLog.logger.error("! deleteContext \(id, privacy: .public): \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
      return
    }
    AssistantConversationStore.clearTitle(for: id)
    AssistantConversationStore.clearLastActivity(for: id)
    if wasCurrent {
      // The library's deleteContext auto-switches the window to the
      // earliest remaining context (or mints a fresh one) — read
      // that back and adopt it as the new pointer.
      let nextName = await session.window.currentContext.name
      currentConversationID = nextName
      AssistantConversationStore.setCurrentContextName(nextName)
      // Re-apply the system prompt + reload the transcript onto the
      // adopted context so the chat surface tracks the switch.
      try? await session.window.setSystemPrompt(Self.systemPrompt)
      await refreshTranscript(window: session.window)
    }
    refreshConversations()
    AssistantLog.logger.info("✕ conversation deleted \(id, privacy: .public)")
  }

  /// Switch the visible chat to `id` (a library context name). Reads
  /// the transcript from disk and updates `messages`.
  func switchConversation(to id: String) async {
    // Update the visible pointer + load the transcript directly out of
    // SQLite right away. The previous code bailed when `id ==
    // currentConversationID`, but on launch `loadConversationsFromDisk`
    // sets `currentConversationID` from UserDefaults WITHOUT loading
    // the transcript (the session is lazy), so clicking the "already
    // selected" row in the sidebar did nothing — the chat stayed
    // empty even though the conversation had content. The disk read
    // is cheap and idempotent: re-clicking just re-reads the same
    // records into `messages`.
    currentConversationID = id
    AssistantConversationStore.setCurrentContextName(id)
    loadTranscriptFromDisk(contextName: id)
    refreshConversations()

    // Then build / switch the session for future sends. Skipping
    // this when no API key is configured: the disk-load already
    // surfaced the visible state; we just can't send into it yet.
    guard isKeyConfigured else { return }
    do {
      let session = try await ensureSession()
      try await session.window.switchContext(name: id)
      try await session.window.setSystemPrompt(Self.systemPrompt)
      await refreshTranscript(window: session.window)
    } catch {
      AssistantLog.logger.error("! switchContext: \(String(describing: error), privacy: .public)")
      errorMessage = "\(error)"
    }
  }

  /// Re-render the sidebar feed from the library + the title /
  /// last-activity caches. Cheap (one `listContexts()` + one
  /// `UserDefaults` read for the two dicts). Called after every
  /// state-mutating operation.
  func refreshConversations() {
    guard let session else { return }
    do {
      let raw = try session.contextStore.listContexts()
      let titles = AssistantConversationStore.titles()
      let activity = AssistantConversationStore.lastActivity()
      conversations = raw
        .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }
        .map { context in
          ConversationListEntry(
            id: context.name,
            title: titles[context.name],
            startedAt: context.startTime,
            lastActivityAt: activity[context.name] ?? context.startTime,
          )
        }
        .sorted { $0.lastActivityAt > $1.lastActivityAt }
    } catch {
      AssistantLog.logger.error("! listContexts: \(String(describing: error), privacy: .public)")
    }
  }

  // MARK: Private

  /// Per-app-launch chat session. Owns the window + the late-bound
  /// executor (the executor is bound to the window at construction
  /// time) and the underlying context store (cached so the sidebar
  /// can list contexts without re-opening SQLite).
  private struct Session {
    let window: ContextWindow
    let executor: LateBoundToolExecutor
    let contextStore: SQLiteContextStore
  }

  /// The chat model. Bumped from `gpt-4.1-mini` to `gpt-5.4` on
  /// 2026-05-29 per user direction. Pulling this into Settings is a
  /// Phase-4 follow-up; for now everything assumes one model.
  /// (Distinct from `AssistantSummarizer.modelName`, which is
  /// `gpt-5.4-mini` for one-shot conversation titling.)
  private static let modelName = "gpt-5.4"

  /// The system prompt that grounds the model in this app's surface.
  /// Kept short and specific; tool affordances are described in each
  /// tool's own schema, not duplicated here. Applied on every
  /// conversation creation / switch via `setSystemPrompt` (which
  /// deadens any prior copy).
  private static let systemPrompt = """
    You are the assistant inside DJ Roomba, a Mac app that manages the \
    user's Apple Music library through a local SQLite store. You can read \
    playlists and tracks, search Apple Music's catalog, see recently \
    played history, and create new app-owned playlists. Prefer calling \
    tools over guessing. When you list tracks back to the user, keep \
    replies short and use plain prose, not large tables.
    """

  @ObservationIgnored private var session: Session?
  @ObservationIgnored private let store: LibraryStore?
  @ObservationIgnored private let catalogIngest: CatalogIngestService?
  /// Weak controller back-reference for the playback / state tools.
  /// Set via `attach(controller:)` immediately after `MusicController`
  /// finishes initializing this service.
  @ObservationIgnored private weak var hostController: MusicController?

  @ObservationIgnored private let keychain = KeychainItem(
    service: "org.sockpuppet.djroomba",
    account: "openai-api-key",
  )

  /// Map one `Record` to a visible `Message`. System prompts are hidden.
  private static func message(from record: Record) -> Message? {
    let role: Message.Role
    switch record.source {
    case .prompt:
      role = .user

    case .modelResponse:
      role = .assistant

    case .toolCall,
         .toolOutput:
      role = .tool

    case .systemPrompt:
      return nil
    }
    return Message(
      id: record.id,
      role: role,
      content: record.content,
      timestamp: record.timestamp,
    )
  }

  /// `~/Library/Application Support/DJRoomba/assistant.sqlite`, mirroring
  /// `AppDatabase.defaultURL()` but in its own file.
  private static func contextStoreURL() throws -> URL {
    let directory = URL.applicationSupportDirectory
      .appending(path: "DJRoomba", directoryHint: .isDirectory)
    try FileManager.default.createDirectory(
      at: directory,
      withIntermediateDirectories: true,
    )
    return directory.appending(
      path: "assistant.sqlite",
      directoryHint: .notDirectory,
    )
  }

  /// Pick which library context to open the window on. Priority:
  /// (1) the UserDefaults pointer (the user's last conversation, if it
  ///     still exists),
  /// (2) the most recent existing assistant context (so a user with
  ///     pre-multi-conversation history lands on it),
  /// (3) the legacy single-conversation name (so the first multi-
  ///     conversation launch on a vanilla install still gets the same
  ///     starting name as Phase 1),
  /// (4) a freshly-minted UUID name.
  ///
  /// Static so it doesn't capture `self` — `ensureSession` calls this
  /// before the `Session` exists.
  private static func pickInitialContextName(
    in store: SQLiteContextStore
  ) throws -> String {
    let existing = try store.listContexts()
      .filter { $0.name.hasPrefix(AssistantConversationStore.contextNamePrefix) }

    if
      let stored = AssistantConversationStore.currentContextName(),
      existing.contains(where: { $0.name == stored })
    {
      return stored
    }
    if let mostRecent = existing.max(by: { $0.startTime < $1.startTime }) {
      return mostRecent.name
    }
    return AssistantConversationStore.legacyContextName
  }

  /// Build the session on first use. Idempotent — a successful call
  /// caches. Re-runs after a key rotation (`session = nil` in
  /// `saveKey`). Multi-conversation aware: opens the SQLite store,
  /// inspects existing contexts, and adopts the one stored in
  /// `AssistantConversationStore.currentContextName()` (or the most
  /// recent existing assistant context, or the legacy single-
  /// conversation name, or finally a freshly-minted one).
  private func ensureSession() async throws -> Session {
    if let session { return session }
    guard let key = (try? keychain.read()) ?? nil, !key.isEmpty else {
      throw GPTServiceError.noAPIKey
    }

    let url = try Self.contextStoreURL()
    let contextStore = try SQLiteContextStore(path: url.path)
    // Same first-run schema bootstrap as `loadConversationsFromDisk` —
    // `pickInitialContextName` reads `contexts` via `listContexts()`,
    // which 500s with "no such table" on a freshly-created
    // `assistant.sqlite`. `initialize()` is `CREATE TABLE IF NOT
    // EXISTS` end-to-end so this is idempotent on an existing file.
    // (`ContextWindow.init` further down also calls `initialize()`,
    // but we read the store before that, so explicit here.)
    try contextStore.initialize()
    let initialContextName = try Self.pickInitialContextName(in: contextStore)

    let executor = LateBoundToolExecutor()
    let model = try OpenAIChatModel(
      model: Self.modelName,
      apiKey: key,
      toolExecutor: executor,
      transport: URLSessionOpenAITransport(session: Self.urlSession),
      serviceTier: Self.serviceTier,
    )
    let window = try ContextWindow(
      store: contextStore,
      contextName: initialContextName,
      model: model,
    )
    executor.bind(window)

    // Apply the system prompt to whichever context we adopted; idempotent
    // (`setSystemPrompt` deadens any prior copy so a re-run never piles
    // them up).
    try await window.setSystemPrompt(Self.systemPrompt)

    // Tools see the controller through a weak provider closure — the
    // closure captures `self` weakly, and `self.hostController` is
    // already weak, so tools never extend the controller's lifetime.
    let toolList = GPTToolRegistration.tools(
      store: store,
      catalogIngest: catalogIngest,
      controllerProvider: { @MainActor [weak self] in self?.hostController },
    )
    for tool in toolList {
      try await window.registerTool(tool)
    }

    let session = Session(window: window, executor: executor, contextStore: contextStore)
    self.session = session
    currentConversationID = initialContextName
    AssistantConversationStore.setCurrentContextName(initialContextName)
    await refreshTranscript(window: window)
    refreshConversations()
    return session
  }

  private func refreshTranscript(window: ContextWindow) async {
    do {
      let records = try await window.allRecords()
      messages = records.compactMap { Self.message(from: $0) }
    } catch {
      // A transcript refresh can't surface usefully — the underlying
      // error would have been raised by the action that just ran.
    }
  }

  /// Detach a summarizer task (gpt-5.4-mini) for the just-archived
  /// conversation. Failure surfaces only to the log — a missing title
  /// leaves the sidebar entry as "Untitled", which is a recoverable
  /// state, not an alert-worthy condition.
  private func summarizeInBackground(messages: [Message], for contextName: String) {
    guard let key = (try? keychain.read()) ?? nil, !key.isEmpty else { return }
    let snapshot = messages
    Task { [weak self] in
      do {
        let title = try await AssistantSummarizer.summarize(
          messages: snapshot,
          apiKey: key,
        )
        AssistantConversationStore.setTitle(title, for: contextName)
        AssistantLog.logger.info(
          "← summary[\(contextName, privacy: .public)]: \(title, privacy: .public)"
        )
        await MainActor.run {
          self?.refreshConversations()
        }
      } catch {
        AssistantLog.logger.error(
          "! summarize \(contextName, privacy: .public): \(String(describing: error), privacy: .public)"
        )
      }
    }
  }

}

// MARK: - GPTServiceError

/// Errors surfaced from `GPTService`'s own boundary (provider errors
/// are passed through verbatim from `ContextWindowOpenAI`).
enum GPTServiceError: Error, CustomStringConvertible {
  case noAPIKey

  var description: String {
    switch self {
    case .noAPIKey:
      "No API key is configured."
    }
  }
}
